# Generated by Django 5.0.2 on 2024-03-05 05:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('study_points', models.PositiveIntegerField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_modified'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CourseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('number', 'Number'), ('time', 'Time')], default='number', editable=False, max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AchievementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_level', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('time_estimate', models.DurationField(blank=True, null=True)),
                ('course_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_levels', to='course.coursemetric')),
            ],
            options={
                'unique_together': {('course_metric', 'achievement_level')},
            },
        ),
        migrations.CreateModel(
            name='InstanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemetric')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'course_metric')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_numbered', models.BooleanField(default=True)),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'parent_chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('achievement_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.achievementmetric')),
                ('progress_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='course.instancemetric')),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.studysession')),
            ],
            options={
                'unique_together': {('progress_instance', 'achievement_metric', 'study_session')},
            },
        ),
    ]
